###############################################################################
# Generate-Missing.ps1 – Create simple EF-based services for models without SPs
###############################################################################
$ErrorActionPreference = 'Stop'
$root  = Split-Path $PSScriptRoot -Parent
$modDir = Join-Path $root 'Models'
$ifDir  = Join-Path $root 'Interfaces'
$svDir  = Join-Path $root 'Services'
$ctDir  = Join-Path $root 'Controllers'

# Models that still need services (no SP package exists)
# These are the services referenced in Program.cs but not generated by SP generator
$missing = @(
    @{ Cls='AeropuertoModel';     Tbl='AEROPUERTOS';        DS='Aeropuertos';        Key='IdAeropuerto';  KT='int' },
    @{ Cls='PistaAterrizajeModel';Tbl='PISTAS_ATERRIZAJE';  DS='PistasAterrizaje';   Key='IdPista';       KT='int' },
    @{ Cls='PuertaEmbarqueModel'; Tbl='PUERTAS_EMBARQUE';   DS='PuertasEmbarque';    Key='IdPuerta';      KT='int' },
    @{ Cls='TerminalAeropuertoModel';Tbl='TERMINALES_AEROPUERTO';DS='Terminales';     Key='IdTerminal';    KT='int' },
    @{ Cls='HangarModel';         Tbl='HANGARES';           DS='Hangares';           Key='IdHangar';      KT='int' },
    @{ Cls='FabricanteAvionModel';Tbl='FABRICANTES_AVION';  DS='FabricantesAviones'; Key='IdFabricante';  KT='int' },
    @{ Cls='ModeloAvionModel';    Tbl='MODELOS_AVION';      DS='ModelosAviones';     Key='IdModelo';      KT='int' },
    @{ Cls='MotorAvionModel';     Tbl='MOTORES_AVION';      DS='MotoresAviones';     Key='IdMotor';       KT='int' },
    @{ Cls='AvionModel';          Tbl='AVIONES';            DS='Aviones';            Key='IdAvion';       KT='int' },
    @{ Cls='MantenimientoAvionModel';Tbl='MANTENIMIENTOS_AVIONES';DS='MantenimientosAviones';Key='IdMantenimiento';KT='int' },
    @{ Cls='FranquiciaEquipajeModel';Tbl='FRANQUICIAS_EQUIPAJE';DS='FranquiciasEquipaje';Key='IdFranquicia';KT='int' },
    @{ Cls='AerolineaModel';      Tbl='AEROLINEAS';         DS='Aerolineas';         Key='IdAerolinea';   KT='int' },
    @{ Cls='AlianzaAerolineaModel';Tbl='ALIANZAS_AEROLINEAS';DS='AlianzasAerolineas';Key='IdAlianza';     KT='int' },
    @{ Cls='TipoAerolineaModel';  Tbl='TIPOS_AEROLINEA';    DS='TiposAerolinea';     Key='IdTipo';        KT='int' },
    @{ Cls='TipoAeropuertoModel'; Tbl='TIPOS_AEROPUERTO';   DS='TiposAeropuerto';    Key='IdTipo';        KT='int' },
    @{ Cls='DiaOperacionModel';   Tbl='DIAS_OPERACION';     DS='DiasOperacion';      Key='IdDia';         KT='int' },
    @{ Cls='ProgramaVueloModel';  Tbl='PROGRAMAS_VUELO';    DS='ProgramasVuelo';     Key='IdPrograma';    KT='int' },
    @{ Cls='FrecuenciaVueloModel';Tbl='FRECUENCIAS_VUELO';  DS='FrecuenciasVuelo';   Key='IdFrecuencia';  KT='int' },
    @{ Cls='TarifaVueloModel';    Tbl='TARIFAS_VUELO';      DS='TarifasVuelo';       Key='IdTarifa';      KT='int' },
    @{ Cls='VueloModel';          Tbl='VUELOS';             DS='Vuelos';             Key='IdVuelo';       KT='int' },
    @{ Cls='CondicionMeteorologicaModel';Tbl='CONDICIONES_METEOROLOGICAS';DS='CondicionesMeteorologicas';Key='IdCondicion';KT='int' },
    @{ Cls='IncidenteVueloModel'; Tbl='INCIDENTES_VUELO';   DS='IncidentesVuelo';    Key='IdIncidente';   KT='int' },
    @{ Cls='RetrasoVueloModel';   Tbl='RETRASOS_VUELO';     DS='RetrasosVuelo';      Key='IdRetraso';     KT='int' },
    @{ Cls='TripulacionVueloModel';Tbl='TRIPULACION_VUELO'; DS='TripulacionVuelo';   Key='IdTripulacionVuelo';KT='int' },
    @{ Cls='TripulacionModel';    Tbl='TRIPULACION';        DS='Tripulacion';        Key='IdTripulacion'; KT='int' },
    @{ Cls='PasajeroModel';       Tbl='PASAJEROS';          DS='Pasajeros';          Key='IdPasajero';    KT='int' },
    @{ Cls='PasajerosRedesSocialesModel';Tbl='PASAJEROS_REDES_SOCIALES';DS='PasajerosRedesSociales';Key='IdRedSocial';KT='int' },
    @{ Cls='PreferenciaIdiomaModel';Tbl='PREFERENCIAS_IDIOMAS';DS='PreferenciasIdiomas';Key='IdPreferencia';KT='int' },
    @{ Cls='AcompanantesViajeModel';Tbl='ACOMPANANTES_VIAJE';DS='AcompanantesViaje'; Key='IdAcompanante'; KT='int' },
    @{ Cls='GruposPasajerosModel';Tbl='GRUPOS_PASAJEROS';   DS='GruposPasajeros';    Key='IdGrupo';       KT='int' },
    @{ Cls='ReservasModel';       Tbl='RESERVAS';           DS='Reservas';           Key='IdReserva';     KT='int' },
    @{ Cls='ReservasPromocionesModel';Tbl='RESERVAS_PROMOCIONES';DS='ReservasPromociones';Key='IdReserva'; KT='int' },
    @{ Cls='HistorialReservasModel';Tbl='HISTORIAL_RESERVAS';DS='HistorialReservas'; Key='IdHistorial';   KT='int' },
    @{ Cls='IncidentesEvidenciaModel';Tbl='INCIDENTES_EVIDENCIA';DS='IncidentesEvidencia';Key='IdEvidencia';KT='int' },
    @{ Cls='AlertasSeguridadModel';Tbl='ALERTAS_SEGURIDAD'; DS='AlertasSeguridad';   Key='IdAlerta';      KT='int' },
    @{ Cls='AccesosAreasRestringidasModel';Tbl='ACCESOS_AREAS_RESTRINGIDAS';DS='AccesosAreasRestringidas';Key='IdAcceso';KT='int' },
    @{ Cls='ObjetosSeguimientoModel';Tbl='OBJETOS_SEGUIMIENTO';DS='ObjetosSeguimiento';Key='IdSeguimiento';KT='int' },
    @{ Cls='CategoriasObjetosModel';Tbl='CATEGORIAS_OBJETOS';DS='CategoriasObjetos'; Key='IdCategoria';   KT='int' },
    @{ Cls='HistorialComunicacionModel';Tbl='HISTORIAL_COMUNICACION';DS='HistorialComunicacion';Key='IdHistorial';KT='int' },
    @{ Cls='MonitoreoAire';       Tbl='MONITOREO_AIRE';     DS='MonitoreoAire';      Key='IdMonitoreo';   KT='int' },
    @{ Cls='MonitoreoRuido';      Tbl='MONITOREO_RUIDO';    DS='MonitoreoRuido';     Key='IdMonitoreo';   KT='int' },
    @{ Cls='IndicadoresDesempenoAmbiental';Tbl='INDICADORES_DESEMPENO_AMBIENTAL';DS='IndicadoresDesempenoAmbiental';Key='IdIndicador';KT='int' },
    @{ Cls='LogsAccesoSistema';   Tbl='LOGS_ACCESO_SISTEMA';DS='LogsAcceso';         Key='IdLog';         KT='int' },
    @{ Cls='TokensAutenticacion'; Tbl='TOKENS_AUTENTICACION';DS='Tokens';            Key='IdToken';       KT='int' },
    @{ Cls='BitacoraCambiosDb';   Tbl='BITACORA_CAMBIOS_DB';DS='BitacoraCambios';    Key='IdCambio';      KT='int' },
    @{ Cls='RespaldosSistema';    Tbl='RESPALDOS_SISTEMA';  DS='Respaldos';          Key='IdRespaldo';    KT='int' },
    @{ Cls='PasajerosSegmentos';  Tbl='PASAJEROS_SEGMENTOS';DS='PasajerosSegmentos'; Key='IdPasajero';    KT='int' },
    @{ Cls='NewsletterEnvios';    Tbl='NEWSLETTER_ENVIOS';  DS='NewsletterEnvios';   Key='IdEnvio';       KT='int' },
    @{ Cls='AnalisisComportamiento';Tbl='ANALISIS_COMPORTAMIENTO';DS='AnalisisComportamiento';Key='IdAnalisis';KT='int' },
    @{ Cls='EstandaresInternacionales';Tbl='ESTANDARES_INTERNACIONALES';DS='EstandaresInternacionales';Key='IdEstandar';KT='int' },
    @{ Cls='CodigosOaciPaises';   Tbl='CODIGOS_OACI_PAISES';DS='CodigosOaci';       Key='IdCodigo';      KT='int' },
    @{ Cls='RevisionesDocumentos';Tbl='REVISIONES_DOCUMENTOS';DS='RevisionesDocumentos';Key='IdRevision'; KT='int' },
    @{ Cls='UsuariosRoles';       Tbl='USUARIOS_ROLES';     DS='UsuariosRoles';      Key='IdUsuarioSistema';KT='int' },
    @{ Cls='RolesPermisosModulos';Tbl='ROLES_PERMISOS_MODULOS';DS='RolesPermisosModulos';Key='IdRolSistema';KT='int' },
    @{ Cls='AlertasOperacionales';Tbl='ALERTAS_OPERACIONALES';DS='AlertasOperacionales';Key='IdAlerta';  KT='int' },
    @{ Cls='AsignacionPistasTiempoReal';Tbl='ASIGNACION_PISTAS_TIEMPO_REAL';DS='AsignacionesPistas';Key='IdAsignacion';KT='int' },
    @{ Cls='CapacidadTerminalTiempoReal';Tbl='CAPACIDAD_TERMINAL_TIEMPO_REAL';DS='CapacidadTerminal';Key='IdCapacidad';KT='int' },
    @{ Cls='CondicionesPistaTiempoReal';Tbl='CONDICIONES_PISTA_TIEMPO_REAL';DS='CondicionesPista';Key='IdCondicion';KT='int' },
    @{ Cls='PosicionesRadar';     Tbl='POSICIONES_RADAR';   DS='PosicionesRadar';    Key='IdPosicion';    KT='int' },
    @{ Cls='TorreControlComunicaciones';Tbl='TORRE_CONTROL_COMUNICACIONES';DS='TorreControl';Key='IdComunicacion';KT='int' },
    @{ Cls='HistorialFlujoTrafico';Tbl='HISTORIAL_FLUJO_TRAFICO';DS='HistorialFlujo';Key='IdHistorial';  KT='int' },
    @{ Cls='PrediccionDemanda';   Tbl='PREDICCION_DEMANDA'; DS='PrediccionDemanda';  Key='IdPrediccion';  KT='int' },
    @{ Cls='ComunicacionesEmergencia';Tbl='COMUNICACIONES_EMERGENCIA';DS='ComunicacionesEmergencia';Key='IdComunicacion';KT='int' },
    @{ Cls='SeriesVueloAsignadas';Tbl='SERIES_VUELO_ASIGNADAS';DS='SeriesVueloAsignadas';Key='IdSerie';  KT='int' }
)

foreach ($m in $missing) {
    $cls  = $m.Cls
    $dsN  = $m.DS
    $keyN = $m.Key
    $kT   = $m.KT
    $base = $cls -replace 'Model$',''
    $svc  = "${base}Service"
    $ifc  = "I${svc}"
    $ctrl = "${base}Controller"

    # Check if already exists (skip if generated by SP generator)
    if (Test-Path (Join-Path $svDir "$svc.cs")) { 
        Write-Host "  EXISTS $svc" -ForegroundColor DarkGray
        continue 
    }

    # Interface
    $ifContent = @"
using Aeropuerto.Backend.Models;

namespace Aeropuerto.Backend.Interfaces
{
    public interface $ifc
    {
        Task<List<$cls>> ListarTodo();
        Task<$cls ?> ObtenerPorId($kT id);
        Task<bool> Insertar($cls m);
        Task<bool> Actualizar($kT id, $cls m);
        Task<bool> Eliminar($kT id);
    }
}
"@
    [System.IO.File]::WriteAllText((Join-Path $ifDir "$ifc.cs"), $ifContent, [System.Text.Encoding]::UTF8)

    # Service (EF-only, no SP)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('using Aeropuerto.Backend.Interfaces;')
    [void]$sb.AppendLine('using Aeropuerto.Backend.Models;')
    [void]$sb.AppendLine('using Aeropuerto.Backend.Data;')
    [void]$sb.AppendLine('using Microsoft.EntityFrameworkCore;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('namespace Aeropuerto.Backend.Services')
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public class $svc : $ifc")
    [void]$sb.AppendLine('    {')
    [void]$sb.AppendLine('        private readonly DBContext _primary;')
    [void]$sb.AppendLine('        private readonly ReplicaDBContext _replica;')
    [void]$sb.AppendLine("        public $svc(DBContext primary, ReplicaDBContext replica) { _primary = primary; _replica = replica; }")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("        public async Task<List<$cls>> ListarTodo()")
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            try { return await _replica.$dsN.ToListAsync(); }")
    [void]$sb.AppendLine('            catch (Exception ex) { Console.WriteLine($"ERROR ListarTodo ' + $cls + ': {ex.Message}"); return new List<' + $cls + '>(); }')
    [void]$sb.AppendLine('        }')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("        public async Task<$cls ?> ObtenerPorId($kT id)")
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            try { return await _replica.$dsN.FindAsync(id); }")
    [void]$sb.AppendLine('            catch (Exception ex) { Console.WriteLine($"ERROR ObtenerPorId ' + $cls + ': {ex.Message}"); return null; }')
    [void]$sb.AppendLine('        }')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("        public async Task<bool> Insertar($cls m)")
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            _primary.$dsN.Add(m);")
    [void]$sb.AppendLine('            await _primary.SaveChangesAsync();')
    [void]$sb.AppendLine('            return true;')
    [void]$sb.AppendLine('        }')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("        public async Task<bool> Actualizar($kT id, $cls m)")
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            _primary.$dsN.Update(m);")
    [void]$sb.AppendLine('            await _primary.SaveChangesAsync();')
    [void]$sb.AppendLine('            return true;')
    [void]$sb.AppendLine('        }')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("        public async Task<bool> Eliminar($kT id)")
    [void]$sb.AppendLine('        {')
    [void]$sb.AppendLine("            var e = await _primary.$dsN.FindAsync(id);")
    [void]$sb.AppendLine('            if (e == null) return false;')
    [void]$sb.AppendLine("            _primary.$dsN.Remove(e);")
    [void]$sb.AppendLine('            await _primary.SaveChangesAsync();')
    [void]$sb.AppendLine('            return true;')
    [void]$sb.AppendLine('        }')
    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine('}')
    [System.IO.File]::WriteAllText((Join-Path $svDir "$svc.cs"), $sb.ToString(), [System.Text.Encoding]::UTF8)

    # Controller
    if (-not (Test-Path (Join-Path $ctDir "$ctrl.cs"))) {
        $cb = [System.Text.StringBuilder]::new()
        [void]$cb.AppendLine('using Microsoft.AspNetCore.Mvc;')
        [void]$cb.AppendLine('using Aeropuerto.Backend.Interfaces;')
        [void]$cb.AppendLine('using Aeropuerto.Backend.Models;')
        [void]$cb.AppendLine('')
        [void]$cb.AppendLine('namespace Aeropuerto.Backend.Controllers')
        [void]$cb.AppendLine('{')
        [void]$cb.AppendLine('    [ApiController]')
        [void]$cb.AppendLine('    [Route("api/[controller]")]')
        [void]$cb.AppendLine("    public class $ctrl : ControllerBase")
        [void]$cb.AppendLine('    {')
        [void]$cb.AppendLine("        private readonly $ifc _svc;")
        [void]$cb.AppendLine("        public $ctrl($ifc svc) { _svc = svc; }")
        [void]$cb.AppendLine('')
        [void]$cb.AppendLine('        [HttpGet]')
        [void]$cb.AppendLine('        public async Task<IActionResult> GetAll() => Ok(await _svc.ListarTodo());')
        [void]$cb.AppendLine('')
        [void]$cb.AppendLine('        [HttpGet("{id}")]')
        [void]$cb.AppendLine("        public async Task<IActionResult> GetById($kT id)")
        [void]$cb.AppendLine('        {')
        [void]$cb.AppendLine('            var item = await _svc.ObtenerPorId(id);')
        [void]$cb.AppendLine('            return item == null ? NotFound() : Ok(item);')
        [void]$cb.AppendLine('        }')
        [void]$cb.AppendLine('')
        [void]$cb.AppendLine('        [HttpPost]')
        [void]$cb.AppendLine("        public async Task<IActionResult> Create([FromBody] $cls m)")
        [void]$cb.AppendLine('        {')
        [void]$cb.AppendLine('            await _svc.Insertar(m);')
        [void]$cb.AppendLine('            return Ok(new { mensaje = "Registro creado correctamente." });')
        [void]$cb.AppendLine('        }')
        [void]$cb.AppendLine('')
        [void]$cb.AppendLine('        [HttpPut("{id}")]')
        [void]$cb.AppendLine("        public async Task<IActionResult> Update($kT id, [FromBody] $cls m)")
        [void]$cb.AppendLine('        {')
        [void]$cb.AppendLine('            await _svc.Actualizar(id, m);')
        [void]$cb.AppendLine('            return Ok(new { mensaje = "Registro actualizado correctamente." });')
        [void]$cb.AppendLine('        }')
        [void]$cb.AppendLine('')
        [void]$cb.AppendLine('        [HttpDelete("{id}")]')
        [void]$cb.AppendLine("        public async Task<IActionResult> Delete($kT id)")
        [void]$cb.AppendLine('        {')
        [void]$cb.AppendLine('            await _svc.Eliminar(id);')
        [void]$cb.AppendLine('            return Ok(new { mensaje = "Registro eliminado correctamente." });')
        [void]$cb.AppendLine('        }')
        [void]$cb.AppendLine('    }')
        [void]$cb.AppendLine('}')
        [System.IO.File]::WriteAllText((Join-Path $ctDir "$ctrl.cs"), $cb.ToString(), [System.Text.Encoding]::UTF8)
    }

    Write-Host "  CREATED $svc (EF-only)" -ForegroundColor Cyan
}
Write-Host "Done generating missing services."
